### PR TITLE
test/test_unit.py: replace hardcoded "python3" executable name

### PR DESCRIPTION
**Pull request by johanneskastl**
do not use `python3`, rather use sys.executable to use the same python version this test is running with

### CODE REVIEW

**Review by ssbarnea — APPROVED** [review]

**Comment by johanneskastl** [comment]
Should I rebase, or will this interfere with the CI?

**Comment by ssbarnea** [comment]
Rebace works fine with GHA, in fact is always a good idea to rebase.

**Comment by johanneskastl** [comment]
Hooray, everything green! Can this be merged?

**Comment by johanneskastl** [comment]
Can someone merge this? Before I have to rebase again :-)

**Review by ssbarnea — APPROVED** [review]

**Pull request merged**
